language: java
before_deploy: "echo rvm_autoupdate_flag=2 >> ~/.rvmrc"
deploy:
  provider: s3
  access_key_id: "AKIAIY5BQWP52Y47JDTA"
  secret_access_key: "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"
  bucket: "S3_Bucket_Jude"
  skip_cleanup: true